spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.190.147.150:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cyx12580.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: warn
    com.totoro: info
  file: log/blog-pro.log
server:
  port: 8081



